cache:
  - bundler
language: ruby
before_install:
  - gem update --system
  - gem install bundler
sudo: false
rvm:
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
  - jruby-19mode
  - jruby-head
  - ruby-head
env:
  global:
    - JRUBY_OPTS="-J-Xmx1024M --debug"
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true

notifications:
  email:
    recipients:
      - thomasvincent@gmail.com
    on_failure: change
    on_success: never
